---
version: "3.9"
services:
  app: &app
    image: app
    build:
      context: src/
      labels:
        # static labels
        io.github.pricesmith.name: app
        io.github.pricesmith.description: lorem ipsum sit amet
        io.github.pricesmith.vendor: pricesmith
        io.github.pricesmith.vcs-url: https://github.com/pricesmith/sso-automation
        # dynamic labels
        io.github.pricesmith.version: ${VERSION}
        io.github.pricesmith.build-date: ${BUILD_DATE}
        io.github.pricesmith.vcs-ref: ${VCS_REF}
        io.github.pricesmith.usage: ${VCS_URL}/blob/${VCS_REF}/README.md
        io.github.pricesmith.license: MIT
        io.github.pricesmith.dockerfile: src/Dockerfile
        io.github.pricesmith.vcs-type: Git

  troubleshooter:
    <<: *app
    entrypoint: /bin/bash
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  linter:
    <<: *app
    entrypoint: /opt/app/linter

  optimistic:
    extends: app
    image: pricesmith/app

  pessimistic:
    extends: app
    image: pricesmith/app:${VERSION}
